version: '3'
services:
  perry-web:
    build:
      context: perry-web
    image: perry-web:latest
    container_name: perry-web
    ports:
      - "9000:9000"
    environment:
      IS_DOCKER: 1
    links:
      - perry-db
  perry-db:
    build:
      context: perry-db
    container_name: perry-db
    image: perry-db:latest
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
